### ISSUE TITLE
name 'subprocess' is not defined

### ISSUE THREAD

**Issue by cpence** [kdani3/i3-gnome-pomodoro#40]
I get the following backtrace when enabling nagbar and switching to a disabled workspace:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/i3-gnome-pomodoro", line 251, in generated_daemon
    i3.main()
  File "/usr/lib/python3.9/site-packages/i3ipc/connection.py", line 514, in main
    raise loop_exception
  File "/usr/lib/python3.9/site-packages/i3ipc/connection.py", line 497, in main
    while not self._event_socket_poll():
  File "/usr/lib/python3.9/site-packages/i3ipc/connection.py", line 477, in _event_socket_poll
    raise e
  File "/usr/lib/python3.9/site-packages/i3ipc/connection.py", line 474, in _event_socket_poll
    self._pubsub.emit(event_name, event)
  File "/usr/lib/python3.9/site-packages/i3ipc/_private/pubsub.py", line 28, in emit
    s['handler'](self.conn, data)
  File "/usr/bin/i3-gnome-pomodoro", line 235, in handler
    show_message("Workspace %s is not allowed during a pomodoro"
  File "/usr/bin/i3-gnome-pomodoro", line 208, in show_message
    Popen('%s -t %s -m "%s"' % (detect_nagbar(), type_, message), shell=True)
  File "/usr/bin/i3-gnome-pomodoro", line 110, in detect_nagbar
    if subprocess.call(["pgrep", "i3"], stdout=devnull) == 0:
NameError: name 'subprocess' is not defined
```

As far as I can tell, when you `import subprocess` you're only importing `Popen`, but then using `call` in `detect_nagbar`? Python's not my forté, though, so I could be wrong.

**Comment by kantord** [comment]
Interesting, this indeed sounds like a bug

**Comment by kantord** [comment]
I can reproduce it :+1:

**Comment by kantord** [comment]
Should be fixed on latest master. Thanks for reporting!

**Comment by cpence** [comment]
Excellent! Thanks for a really helpful tool!
